language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
os:
  - linux
  - osx
env:
  - FARMHASH_NOMARCH=y
  - FARMHASH_NOMARCH=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
sudo: false
osx_image: xcode8
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
